# Generated by Django 5.1.1 on 2024-11-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0003_featureproject_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='donation.jpeg', upload_to='Projectlist'),
        ),
    ]
